name: Generate Datas

on:
  schedule: # execute every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Snake Animation
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.gemaquejr }}
          
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
