name: Generate Datas

on:
  schedule: # execute every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Set up Environment
        run: |
          # Create an environment file
          echo "GITHUB_USER_NAME=gemaquejr" > env.txt
          echo "GIF_OUT_PATH=dist/github-contribution-grid-snake.gif" >> env.txt
          echo "SVG_OUT_PATH=dist/github-contribution-grid-snake.svg" >> env.txt

      - name: Snake Animation
        id: snake-gif
        run: |
          source env.txt
          # Use the environment variables in your action
          echo "Generating Snake Animation for $GITHUB_USER_NAME"
          Platane/snk
        shell: bash

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
